services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    networks:
      - prometheus
  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    hostname: grafana
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 80:3000
    networks:
      - prometheus
networks:
  prometheus:
    external: true
